name: Build & Deploy Classifier

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/classifier.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Normalize tag   # <- 선택
        run: |
          echo "IMAGE=$(echo '${{ secrets.DOCKER_IMAGENAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_SHA=$(echo '${{ secrets.DOCKER_IMAGENAME }}' | tr '[:upper:]' '[:lower:]'):${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE }},${{ env.IMAGE_SHA }}

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            mkdir -p ~/classifier-data/annot
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > ~/classifier-data/classifier.env

            docker pull ${{ env.IMAGE }}
            docker stop classifier || true
            docker rm classifier || true
            docker run -d --name classifier \
              --env-file ~/classifier-data/classifier.env \
              -v ~/classifier-data/annot:/app/static/annot \
              -p 8100:8000 \
              ${{ env.IMAGE }}
