name: Build & Deploy Classifier

on:
  push:
    branches: [ main ]
    paths:
      - 'classifier/**'
      - '.github/workflows/classifier.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: classifier/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/classifier:latest

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            mkdir -p ~/classifier-data/annot
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > ~/classifier-data/classifier.env

            docker pull ghcr.io/${{ github.repository_owner }}/classifier:latest
            docker stop classifier || true
            docker rm classifier || true
            docker run -d --name classifier \
              --env-file ~/classifier-data/classifier.env \
              -v ~/classifier-data/annot:/app/static/annot \
              -p 8000:8000 \
              ghcr.io/${{ github.repository_owner }}/classifier:latest
